---
name: Perl_WebFetch_RSS
# yamllint disable rule:line-length
on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - 'submodules/RSS/**'
  pull_request:
    paths:
      - 'submodules/RSS/**'
  workflow_dispatch:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest]  # , macos-latest, windows-latest]
        perl: ['5.36']
        exclude:
          - runner: windows-latest
            perl: '5.36'
    runs-on: ${{matrix.runner}}
    name: OS ${{matrix.runner}} Perl ${{matrix.perl}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          distribution: >
            ${{ ( startsWith( matrix.runner, 'windows-' )
            && 'strawberry' ) || 'default' }}
      - name: Show Perl Version
        run: |
          perl -v
      - name: Install external dependency
        if: ${{ matrix.runner == 'ubuntu-latest' }}
        run: |
          sudo apt update
          sudo apt install -y libdb-dev
      # - name: Install dependency for OSX
      #   if:  ${{ matrix.runner == 'macos-latest' }}
      #   run: brew install berkeley-db
      - name: Install Dist::Zilla
        run: |
          cpanm -v
          cpanm --dev --notest ExtUtils::MakeMaker~'>= 7.65_02'  # use dev release with fix for spurious errors
          cpanm --notest Dist::Zilla Test::Pod Pod::Markdown
          dzil --version
      - name: Install Authordeps Modules
        run: |
          cd submodules/RSS
          dzil authordeps --missing | cpanm --notest
      - name: Install Listdeps Modules
        run: |
          cd submodules/RSS
          pwd
          ls -l
          dzil listdeps --missing | cpanm --notest
      - name: Show Errors on Windows
        if: ${{ failure() && startsWith( matrix.runner, 'windows-')}}
        run: |
           ls -l C:/Users/
           ls -l C:/Users/RUNNER~1/
           cat C:/Users/runneradmin/.cpanm/work/*/build.log
      - name: Show Errors on Ubuntu
        if: ${{ failure() && startsWith( matrix.runner, 'ubuntu-')}}
        run: |
           cat /home/runner/.cpanm/work/*/build.log
      - name: Show Errors on OSX
        if: ${{ failure() && startsWith( matrix.runner, 'macos-')}}
        run: |
           cat  /Users/runner/.cpanm/work/*/build.log
      - name: Run tests
        run: |
          cd submodules/RSS
          dzil test
